name: dds
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.7.7
  # - tensorflow-gpu=1.14
  - tensorflow=1.14
  - flask
  - munch
  - networkx
  - pyyaml
  - requests
  - pip
  - scikit-learn
  - ffmpeg
  - pip:
    - opencv-contrib-python
 